##
#	Configuration of OSPF
##

router ospf
 ospf router-id 10.0.2.1
 network 192.168.11.2/32 area 0
 network 192.168.12.2/32 area 0
 network 10.0.2.1/32 area 0


##
#	Configuration of BGP
##

router bgp 65000
 bgp router-id 10.0.2.1
 neighbor 100.64.0.1 remote-as 65000
 neighbor 100.64.0.1 update-source lo
 neighbor 100.64.0.2 remote-as 65000
 neighbor 100.64.0.2 update-source lo

 address-family l2vpn evpn
  neighbor 100.64.0.1 activate
  neighbor 100.64.0.1 route-reflector-client
  neighbor 100.64.0.2 activate
  neighbor 100.64.0.2 route-reflector-client

